package inf112.skeleton.app.Boards.Board;

public enum SquareType {
    ROTATE_CW, ROTATE_CCW, REPAIR, DOUBLE_REPAIR, CONVEYOR_WEST, CONVEYOR_EAST, CONVEYOR_NORTH, CONVEYOR_SOUTH, WALL_WEST, WALL_EAST, WALL_NORTH, WALL_SOUTH, HOLE, DOUBLE_CONVEYOR_NORTH, DOUBLE_CONVEYOR_SOUTH, DOUBLE_CONVEYOR_WEST, DOUBLE_CONVEYOR_EAST, FLAG
}